# Generated by Django 5.1.4 on 2025-01-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DW_app', '0003_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='price',
            field=models.FloatField(default=100),
        ),
    ]
