# Generated by Django 5.1.4 on 2025-01-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DW_app', '0004_clothes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='photo',
            field=models.CharField(max_length=255),
        ),
    ]
