# Generated by Django 5.1.4 on 2025-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DW_app', '0006_customer_landmark_customer_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
