# Generated by Django 5.1.4 on 2025-01-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DW_app', '0007_alter_customer_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='order',
        ),
        migrations.AddField(
            model_name='clothes',
            name='order',
            field=models.ManyToManyField(null=True, related_name='cloth_order', to='DW_app.order'),
        ),
    ]
