# Generated by Django 5.1.4 on 2025-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DW_app', '0009_customer_is_mob_num_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_num',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
