# Generated by Django 5.1.4 on 2025-01-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DW_app', '0010_alter_customer_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='order',
            field=models.ManyToManyField(related_name='cloth_order', to='DW_app.order'),
        ),
    ]
